from pathlib import Path
'''
if use_cache:
    print("Utilizzo la cache di top10categorie reuters")
    if Path(r"cacheTop10.txt").exists():
        with open("cacheTop10.txt", 'r') as f:
            top10 = [line.rstrip('\n') for line in f]
        return top10
    else:
        print("Ma non esiste, quindi procedo a trovarla")
        
# Cacho la lista
    with open("cacheTop10.txt", 'w') as f:
        for s in listaNomiCategorieTop10:
            f.write(str(s).replace("[", "").replace("]", "").replace("'", "") + '\n')

'''
import os
import Preprocessing

''' ReutersLoadFiles loads all files from reuters21578 folder and it splits them in two main subfolders:
        -training-set
        -test-set

    It uses Preprocessing.top10categories(...) to extract the 10 more frequent categories among all samples.

    Please ensure that everytime this module is run, files and folders that were generated by previous executions must be deleted.

        '''


def Reuters_load_files():
    current_working_folder = os.getcwd()
    docfiles = [current_working_folder + '/reuters21578/reut2-000.sgm',
                current_working_folder + '/reuters21578/reut2-001.sgm',
                current_working_folder + '/reuters21578/reut2-002.sgm',
                current_working_folder + '/reuters21578/reut2-003.sgm',
                current_working_folder + '/reuters21578/reut2-004.sgm',
                current_working_folder + '/reuters21578/reut2-005.sgm',
                current_working_folder + '/reuters21578/reut2-006.sgm',
                current_working_folder + '/reuters21578/reut2-007.sgm',
                current_working_folder + '/reuters21578/reut2-008.sgm',
                current_working_folder + '/reuters21578/reut2-009.sgm',
                current_working_folder + '/reuters21578/reut2-010.sgm',
                current_working_folder + '/reuters21578/reut2-011.sgm',
                current_working_folder + '/reuters21578/reut2-012.sgm',
                current_working_folder + '/reuters21578/reut2-013.sgm',
                current_working_folder + '/reuters21578/reut2-014.sgm',
                current_working_folder + '/reuters21578/reut2-015.sgm',
                current_working_folder + '/reuters21578/reut2-016.sgm',
                current_working_folder + '/reuters21578/reut2-018.sgm',
                current_working_folder + '/reuters21578/reut2-019.sgm',
                current_working_folder + '/reuters21578/reut2-020.sgm',
                current_working_folder + '/reuters21578/reut2-021.sgm']
    print(
        'Analizzo i file per controllare quali sono le 10 categorie più frequenti:(potrebbe richieder qualche minuto)')

    listaNomiCategorieTop10 = Preprocessing.top10categories(current_working_folder, docfiles)

    print('lista dei tag riferiti alle 10 categorie più frequenti:')
    for y in listaNomiCategorieTop10:
        print('<D>' + str(y).rstrip("']").lstrip("['") + '</D>')

    print('Orgnizzo file in cartelle:')

    for x in docfiles:
        io = open(x, 'r')
        strr = io.read()
        docs = strr.split("</REUTERS>")
        for sample in docs:
            if any('<D>' + str(y).rstrip("']").lstrip("['") + '</D>' in sample for y in listaNomiCategorieTop10):
                if not os.path.exists(current_working_folder + "/data-set"):
                    os.makedirs(current_working_folder + "/data-set")
                if 'LEWISSPLIT="TRAIN"' in sample and 'TOPICS="YES"' in sample:
                    if not os.path.exists(current_working_folder + "/data-set/training-set"):
                        os.makedirs(current_working_folder + "/data-set/training-set")
                    for y in listaNomiCategorieTop10:
                        if '<D>' + str(y).rstrip("']").lstrip("['") + '</D>' in sample:
                            if not os.path.exists(current_working_folder + "/data-set/training-set/" + str(y).rstrip(
                                    "']").lstrip("['")):
                                os.makedirs(
                                    current_working_folder + "/data-set/training-set/" + str(y).rstrip("']").lstrip(
                                        "['"))
                            os.chdir(
                                current_working_folder + "/data-set/training-set/" + str(y).rstrip("']").lstrip("['"))
                            indexTitle = sample.index("NEWID=")
                            endTitle = sample.index('">')
                            title = '0' + sample[indexTitle + 7:endTitle]
                            body = Preprocessing.body_extractor(sample)
                            output = open(title + '.txt', 'w')
                            output.write(sample)
                elif 'LEWISSPLIT="TEST"' in sample and 'TOPICS="YES"' in sample:
                    if not os.path.exists(current_working_folder + "/data-set/test-set"):
                        os.makedirs(current_working_folder + "/data-set/test-set")
                    for y in listaNomiCategorieTop10:
                        if '<D>' + str(y).rstrip("']").lstrip("['") + '</D>' in sample:
                            if not os.path.exists(current_working_folder + "/data-set/test-set/" + str(y).rstrip(
                                    "']").lstrip("['")):
                                os.makedirs(
                                    current_working_folder + "/data-set/test-set/" + str(y).rstrip("']").lstrip("['"))
                            os.chdir(current_working_folder + "/data-set/test-set/" + str(y).rstrip("']").lstrip("['"))
                            indexTitle = sample.index("NEWID=")
                            endTitle = sample.index('">')
                            title = '0' + sample[indexTitle + 7:endTitle]
                            body = Preprocessing.body_extractor(sample)
                            output = open(title + '.txt', 'w')
                            output.write(body)
    print('Organizzazione in cartelle completata.')



def warmup():
    if Path(r"data-set/").exists():
        print("Dataset reuter presente")
    else:
        print("Dataset reuter NON presente")
        Reuters_load_files()

if __name__ == '__main__':
    warmup()
